### ISSUE TITLE
Unknown exception in JEventSource

### ISSUE THREAD

**Issue by DraTeots** [JeffersonLab/JANA2#53] opened 2020-03-05 01:43 UTC
Hi! 
When I'm doning like this in the event source:

```c++
try {
   foo = std::stod(event_tokens[1]);
}
catch(std::exception &ex) {
   auto err_msg = fmt::format("Error parsing event at line '{}', parsing error message is: {} ", this->started_at_line, ex.what());
   throw std::runtime_error(err_msg);
}
```

JANA2 creates an output:

```
[FATAL] JWorker: Exception: Unknown exception in JEventSource::GetEvent()

  Plugin:         lund_reader.so
  Backtrace:

     `- make_backtrace(std::ostream&) (0x55c48eb60d26)
      `- JException::JException(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) (0x55c48eb6128d)
       `- JEventSourceArrow::execute(JArrowMetrics&, unsigned long) (0x55c48eb885fa)
        `- JWorker::loop() (0x55c48eb8cad6)
         `- /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x7f3160ee266f)
          `- /lib/x86_64-linux-gnu/libpthread.so.0 (0x7f31609f56db)
           `- clone (0x7f316071e88f)
```

Problem - final message completely hides the real problem from users.

**Comment by faustus123** [comment] 2020-03-05 13:34
Looks like a duplicate of #52.

**Closed by faustus123** 2020-03-05 13:34 UTC
