### ISSUE TITLE
JANA2 installation fails because of libnuma

### ISSUE THREAD

**Issue by DraTeots** [JeffersonLab/JANA2#9] opened 2019-03-07 08:59 UTC
```
(venv) romanov@romanov-hpc:~/eic/ejpm$ python run_ejpm.py install jana

Current status of the packet and dependencies:
   jana   : not installed

 INSTALLATION ORDER:
   jana   : /home/romanov/eic/jana/jana-master


=========================================
 SETTING ENVIRONMENT
=========================================

Updating python environment for 'clhep'
   update_env:     set $CLHEP = '/home/romanov/eic/clhep/clhep-master'
   update_env:     set $CLHEPPATH = '/home/romanov/eic/clhep/clhep-master'
   update_env:     set $CLHEP_INCLUDE_DIR = '/home/romanov/eic/clhep/clhep-master/include'
   update_env:     set $CLHEP_LIB_DIR = '/home/romanov/eic/clhep/clhep-master/lib'
   update_env: prepend $PATH by '/home/romanov/eic/clhep/clhep-master/bin'
   update_env: prepend $LD_LIBRARY_PATH by '/home/romanov/eic/clhep/clhep-master/lib'
Updating python environment for 'ejana'
   update_env: prepend $JANA_PLUGIN_PATH by 'plugins'
   update_env: prepend $PATH by 'bin'
Updating python environment for 'genfit'
   update_env:     set $GENFIT = '/home/romanov/eic/genfit/genfit-master'
   update_env:     set $GENFIT_DIR = '/home/romanov/eic/genfit/genfit-master'
   update_env:  append $LD_LIBRARY_PATH by '/home/romanov/eic/genfit/genfit-master/lib'
   update_env:  append $LD_LIBRARY_PATH by '/home/romanov/eic/genfit/genfit-master/lib64'
Updating python environment for 'jana'
   update_env:     set $JANA_HOME = '/home/romanov/eic/jana/jana-master'
   update_env:  append $JANA_PLUGIN_PATH by '$JANA_HOME/plugins'
   update_env: prepend $PATH by '$JANA_HOME/bin'
Updating python environment for 'rave'
   update_env:     set $RAVEPATH = '/home/romanov/eic/rave/rave-master'
   update_env: prepend $CMAKE_PREFIX_PATH by '/home/romanov/eic/rave/rave-master/share/rave'
   update_env: prepend $LD_LIBRARY_PATH by '/home/romanov/eic/rave/rave-master/lib'
Updating python environment for 'root'
   update_env: RawText step will update env
   update_env:     set $ROOTSYS = '/home/romanov/eic/root/root-v6-16-00'
   update_env: prepend $PATH by '/home/romanov/eic/root/root-v6-16-00/bin'
   update_env: prepend $LD_LIBRARY_PATH by '/home/romanov/eic/root/root-v6-16-00/lib'
   update_env: prepend $DYLD_LIBRARY_PATH by '/home/romanov/eic/root/root-v6-16-00/lib'
   update_env: prepend $PYTHONPATH by '/home/romanov/eic/root/root-v6-16-00/lib'
   update_env: prepend $CMAKE_PREFIX_PATH by '/home/romanov/eic/root/root-v6-16-00'
   update_env: prepend $JUPYTER_PATH by '/home/romanov/eic/root/root-v6-16-00/etc/notebook'
=========================================
 INSTALLING : jana
=========================================

EXECUTING:
mkdir -p /home/romanov/eic/jana/src/master
Execution done. Return code = 0

EXECUTING:
git clone --depth 1 -b master https://github.com/JeffersonLab/JANA2.git /home/romanov/eic/jana/src/master
Cloning into '/home/romanov/eic/jana/src/master'...
remote: Enumerating objects: 1303, done.
remote: Counting objects: 100% (1303/1303), done.
remote: Compressing objects: 100% (637/637), done.
remote: Total 1303 (delta 508), reused 1242 (delta 491), pack-reused 0
Receiving objects: 100% (1303/1303), 2.93 MiB | 12.59 MiB/s, done.
Resolving deltas: 100% (508/508), done.
Execution done. Return code = 0

EXECUTING:
mkdir -p /home/romanov/eic/jana/build/master
Execution done. Return code = 0

WORKDIR:/home/romanov/eic/jana/src/master

EXECUTING:
scons install -j8 PREFIX=/home/romanov/eic/jana/jana-master VARIANT-DIR=/home/romanov/eic/jana/build/master
scons: Reading SConscript files ...
sbms : Applying settings for platform Linux
sbms : Making jana_config.h in src/.Linux_LinuxMint19.1-x86_64-gcc7/JANA
sbms : Making jana-config in /home/romanov/eic/jana/jana-master/bin
sbms : Making setenv.csh in /home/romanov/eic/jana/jana-master
sbms : Making setenv.sh in /home/romanov/eic/jana/jana-master
scons: done reading SConscript files.
scons: Building targets ...
Installing [/home/romanov/eic/jana/jana-master/include/JANA/JEventProcessor.h]
Installing [/home/romanov/eic/jana/jana-master/include/JANA/JApplication.h]
Installing [/home/romanov/eic/jana/jana-master/include/JANA/JSignalHandler.h]
Installing [/home/romanov/eic/jana/jana-master/include/JANA/JVersion.h]
Installing [/home/romanov/eic/jana/jana-master/include/JANA/JCpuInfo.h]
Installing [/home/romanov/eic/jana/jana-master/include/JANA/JEvent.h]
Installing [/home/romanov/eic/jana/jana-master/include/JANA/JEventSource.h]
Installing [/home/romanov/eic/jana/jana-master/include/JANA/JEventSourceGenerator.h]
Installing [/home/romanov/eic/jana/jana-master/include/JANA/JLogger.h]
Installing [/home/romanov/eic/jana/jana-master/include/JANA/JParameterManager.h]
Installing [/home/romanov/eic/jana/jana-master/include/JANA/JResourcePool.h]
Installing [/home/romanov/eic/jana/jana-master/include/JANA/JResourcePoolSimple.h]
Installing [/home/romanov/eic/jana/jana-master/include/JANA/JStatus.h]
Installing [/home/romanov/eic/jana/jana-master/include/JANA/JEventSourceManager.h]
Installing [/home/romanov/eic/jana/jana-master/include/JANA/JException.h]
Installing [/home/romanov/eic/jana/jana-master/include/JANA/JFactoryGenerator.h]
Installing [/home/romanov/eic/jana/jana-master/include/JANA/JParameter.h]
Installing [/home/romanov/eic/jana/jana-master/include/JANA/JResettable.h]
Installing [/home/romanov/eic/jana/jana-master/include/JANA/JQueueSimple.h]
Installing [/home/romanov/eic/jana/jana-master/include/JANA/JThread.h]
Installing [/home/romanov/eic/jana/jana-master/include/JANA/JThreadManager.h]
Compiling  [src/lib/JANA/JCpuInfo.cc]
Installing [/home/romanov/eic/jana/jana-master/include/JANA/JFactorySet.h]
Installing [/home/romanov/eic/jana/jana-master/include/JANA/JFactoryT.h]
Installing [/home/romanov/eic/jana/jana-master/include/JANA/JFunctions.h]
Installing [/home/romanov/eic/jana/jana-master/include/JANA/JObject.h]
Installing [/home/romanov/eic/jana/jana-master/include/JANA/JQueue.h]
Installing [/home/romanov/eic/jana/jana-master/include/JANA/JQueueSet.h]
Installing [/home/romanov/eic/jana/jana-master/include/JANA/JTask.h]
Installing [/home/romanov/eic/jana/jana-master/include/JANA/JFactory.h]
Compiling  [src/programs/jana/jana.cc]
Compiling  [src/lib/JANA/JApplication.cc]
Compiling  [src/lib/JANA/JEvent.cc]
Compiling  [src/programs/jana/MyProcessor.cc]
Compiling  [src/lib/JANA/JEventSource.cc]
Compiling  [src/lib/JANA/JEventSourceManager.cc]
Compiling  [src/lib/JANA/JException.cc]
Compiling  [src/lib/JANA/JFactoryGenerator.cc]
Compiling  [src/lib/JANA/JFactorySet.cc]
Compiling  [src/lib/JANA/JFunctions.cc]
Compiling  [src/lib/JANA/JObject.cc]
Compiling  [src/lib/JANA/JParameter.cc]
Compiling  [src/lib/JANA/JParameterManager.cc]
Compiling  [src/lib/JANA/JQueueSet.cc]
Compiling  [src/lib/JANA/JQueueSimple.cc]
Compiling  [src/lib/JANA/JQueueWithBarriers.cc]
Compiling  [src/lib/JANA/JQueueWithLock.cc]
Compiling  [src/lib/JANA/JStatus.cc]
Compiling  [src/lib/JANA/JThread.cc]
Compiling  [src/lib/JANA/JThreadManager.cc]
Installing [/home/romanov/eic/jana/jana-master/bin/mkclass]
Installing [/home/romanov/eic/jana/jana-master/bin/mkplugin]
Compiling  [src/programs/playground/playground.cc]
src/lib/JANA/JStatus.cc: In member function ‘void JStatus::SendReport(std::stringstream&)’:
src/lib/JANA/JStatus.cc:322:8: warning: ignoring return value of ‘ssize_t write(int, const void*, size_t)’, declared with attribute warn_unused_result [-Wunused-result]
   write(fd, ss.str().c_str(), ss.str().length()+1);
   ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Installing [/home/romanov/eic/jana/jana-master/include/JANA/JEventSourceGeneratorT.h]
Installing [/home/romanov/eic/jana/jana-master/include/JANA/JQueueWithBarriers.h]
Installing [/home/romanov/eic/jana/jana-master/include/JANA/JQueueWithLock.h]
Installing [/home/romanov/eic/jana/jana-master/include/JANA/JSourceFactoryGenerator.h]
Installing [/home/romanov/eic/jana/jana-master/include/JExample2/JEventProcessor_example2.h]
Installing [/home/romanov/eic/jana/jana-master/include/JExample2/JEventSource_example2.h]
Installing [/home/romanov/eic/jana/jana-master/include/JExample2/JFactoryGenerator_example2.h]
Installing [/home/romanov/eic/jana/jana-master/include/JExample2/MyCluster.h]
Installing [/home/romanov/eic/jana/jana-master/include/JExample2/MyEvent.h]
Installing [/home/romanov/eic/jana/jana-master/include/JExample2/MyHit.h]
Installing [/home/romanov/eic/jana/jana-master/include/JTest/JEventProcessor_jana_test.h]
Installing [/home/romanov/eic/jana/jana-master/include/JTest/JEventSource_jana_test.h]
Installing [/home/romanov/eic/jana/jana-master/include/JTest/JEvent_test.h]
Installing [/home/romanov/eic/jana/jana-master/include/JTest/JFactoryGenerator_jana_test.h]
Installing [/home/romanov/eic/jana/jana-master/include/JTest/JSourceObject.h]
Installing [/home/romanov/eic/jana/jana-master/include/JTest/JSourceObject2.h]
Installing [/home/romanov/eic/jana/jana-master/include/JTest/JTestMain.h]
Installing [/home/romanov/eic/jana/jana-master/include/JTest/jana_test.h]
Installing [/home/romanov/eic/jana/jana-master/include/JTest/jana_test_factory.h]
Installing [/home/romanov/eic/jana/jana-master/include/janarate/JEventProcessorJANARATE.h]
Compiling  [src/examples/JExample1/JExample1.cc]
Compiling  [src/examples/JExample2/JEventSource_example2.cc]
Compiling  [src/examples/JExample2/JExample2.cc]
Compiling  [src/examples/JExample2/MyCluster.cc]
Compiling  [src/plugins/JTest/JEventProcessor_jana_test.cc]
Compiling  [src/plugins/JTest/JEventSource_jana_test.cc]
Compiling  [src/plugins/JTest/JTestMain.cc]
Compiling  [src/plugins/JTest/jana_test_factory.cc]
Compiling  [src/plugins/janapy/janapy.cc]
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
Archiving  [/home/romanov/eic/jana/build/master/lib/JANA/libJANA.a]
Ranlib     [/home/romanov/eic/jana/build/master/lib/JANA/libJANA.a]
Compiling  [src/plugins/janarate/JEventProcessorJANARATE.cc]
Installing [/home/romanov/eic/jana/jana-master/lib/libJANA.a]
Linking    [/home/romanov/eic/jana/build/master/programs/playground/playground]
Linking    [/home/romanov/eic/jana/build/master/examples/JExample2/JExample2.so]
/home/romanov/eic/jana/jana-master/lib/libJANA.a(JCpuInfo.o): In function `JCpuInfo::GetNumaNodeID()':
/home/romanov/eic/jana/src/master/src/lib/JANA/JCpuInfo.cc:65: undefined reference to `numa_available'
/home/romanov/eic/jana/src/master/src/lib/JANA/JCpuInfo.cc:68: undefined reference to `numa_node_of_cpu'
/home/romanov/eic/jana/jana-master/lib/libJANA.a(JCpuInfo.o): In function `JCpuInfo::GetNumNumaNodes()':
/home/romanov/eic/jana/src/master/src/lib/JANA/JCpuInfo.cc:77: undefined reference to `numa_available'
/home/romanov/eic/jana/src/master/src/lib/JANA/JCpuInfo.cc:80: undefined reference to `numa_num_configured_nodes'
collect2: error: ld returned 1 exit status
scons: *** [/home/romanov/eic/jana/build/master/programs/playground/playground] Error 1
src/plugins/janarate/JEventProcessorJANARATE.cc: In member function ‘virtual void JEventProcessorJANARATE::Process(const std::shared_ptr<const JEvent>&)’:
src/plugins/janarate/JEventProcessorJANARATE.cc:88:9: warning: ignoring return value of ‘int fscanf(FILE*, const char*, ...)’, declared with attribute warn_unused_result [-Wunused-result]
   fscanf(fp, "%*s %ld %ld %ld %ld", &a[0], &a[1], &a[2], &a[3]);
   ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
scons: building terminated because of errors.
Execution done. Return code = 2

ERROR
: Command return code != 0. COMMAND CONTENT:
scons install -j8 PREFIX=/home/romanov/eic/jana/jana-master VARIANT-DIR=/home/romanov/eic/jana/build/master
```

**Comment by nathanwbrei** [comment] 2019-03-07 17:14
You shouldn't be seeing that error because scons is supposed to do a test compile to see if it can find numa.h and libnuma. If it can't, then it leaves HAVE_NUMA unset, and then all those functions get stripped out by the preprocessor. Try running scons SHOWBUILD=1.

**Comment by nathanwbrei** [comment] 2019-03-07 18:09
I just reproduced this.

**Comment by nathanwbrei** [comment] 2019-03-07 18:55
Temporary workaround: add the following to ejana/.../src/SBMS/sbms.py:AddJANA()

AddLinkFlags(env, "-lnuma")

The longer-term fix involves updating jana-config to include -lnuma as a link flag when HAVE_NUMA=1

**Comment by nathanwbrei** [comment] 2019-03-07 22:11
I've added the fix. Once you verify that it works for you, we can close this issue.

**Comment by DraTeots** [comment] 2019-03-12 20:31
I'm about to create a docker image to check this...

**Comment by DraTeots** [comment] 2019-03-13 17:40
Dockerfile got delayed. Will get you posted.

**Comment by faustus123** [comment] 2019-05-01 12:36
Any final motion on this so we can close this issue?

**Comment by DraTeots** [comment] 2019-05-01 19:06
Just made ubuntu CI container. Confirm, it works, no problems.

**Closed** 2019-06-10 17:19 UTC
